# Generated by Django 3.2.6 on 2021-08-17 07:00

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Client',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('full_name', models.CharField(max_length=255)),
                ('date_of_birth', models.DateField()),
                ('gender', models.CharField(choices=[('male', 'erkak'), ('female', 'ayol')], max_length=6)),
                ('passport', models.CharField(max_length=255, unique=True)),
                ('telfon', models.CharField(max_length=255)),
                ('qayerga', models.CharField(choices=[('Qirgiziston', 'Qirgiziston'), ('Boshqa', 'Boshqa')], max_length=255)),
                ('test_olindi', models.DateTimeField()),
                ('natija_chiqdi', models.DateTimeField()),
                ('qrcode', models.ImageField(blank=True, upload_to='qrcode/')),
            ],
            options={
                'ordering': ('-id',),
            },
        ),
        migrations.CreateModel(
            name='Info',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('research_method', models.CharField(max_length=255)),
                ('name_of_labaratory', models.CharField(max_length=255)),
                ('head_of_labaratory', models.CharField(max_length=255)),
            ],
        ),
    ]
